### ISSUE TITLE
Filter search results based on curation status

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#10]
It would be very helpful for focusing on papers that still need to be curated if there was an option to filter on curation status.

Curation status could be determined from the curation status form in postgres, or for GO, from the paper IDs in the gene association file.

**Comment by draciti** [comment]
I agree. We could also add a link in the curation status form that will open up the paper directly 

![screen shot 2015-09-16 at 11 50 24 am](https://cloud.githubusercontent.com/assets/901243/9914938/33b789ca-5c69-11e5-9c08-3414c0af86c4.png)
in TPC

**Comment by goldturtle** [comment]
Daniela's issue would need to be resolved by Juancarlos.
Kimberly's issue is VERY WormBase specific. One would need to introduce user-customizable filters.

**Comment by goldturtle** [comment]
Issue should be addressed from the WormBase side, not TPC side. If TPC is used more by AGR and not just one MOD, then we could revisit this issue.
