### ISSUE TITLE
'Info' dialog box comes up too often

### ISSUE THREAD

**Issue by rankishore** [WormBase/textpresso#104]
The 'Info' dialog box comes up with every session (not sure exactly how long one session is in TPC), telling me which literatures I have chosen, which is a bit annoying since it's extra clicking to make it go away (I have 'don't show this again' on).  Can the system remember a User's preferences and not show this dialog box?

**Comment by valearna** [comment]
The "don't show again" option is now saved in the db for logged in users or stored in a cookie for anonymous users.

**Comment by goldturtle** [comment]
Seems to be resolved.
