### ISSUE TITLE
Getting logged out while search is combining results

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#105]
Hi,

I am trying to perform some searches on https://textpressocentral.org/tpc/search but am getting logged out after the search says it is combining the results.

Here is a screenshot of my search parameters:

<img width="1660" alt="screen shot 2017-10-31 at 2 16 01 pm" src="https://user-images.githubusercontent.com/1730534/32241312-30bdd832-be46-11e7-8ba8-8f5464e42d98.png">

**Comment by valearna** [comment]
The problem was related to old files in your user uploads directory. I removed those files and the bug should be fixed. Let me know if you can perform searches now.

**Comment by vanaukenk** [comment]
Yes, the searches are working properly now.   Thanks @valearna !

**Comment by chris-grove** [comment]
@vanaukenk 
Seems like this can be closed?
