### ISSUE TITLE
WB Papers missing in TPC

### ISSUE THREAD

**Issue by chris-grove** [WormBase/textpresso#106]
The following papers are not returned by TPC search:

WBPaper00049531
WBPaper00050796
WBPaper00028578
WBPaper00042411

**Comment by vanaukenk** [comment]
Also:

WBPaper00048489

**Comment by valearna** [comment]
We set up the new Textpressocentral pipeline and updated the corpus. These papers are now available.

**Comment by chris-grove** [comment]
@valearna 
Great! Thanks!
