### ISSUE TITLE
Accept PMID:nnnnnnn as format for Accession

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#107]
Hi,

Would it be possible to accept Accessions in the filter section in the format 'PMID:nnnnnnnnn', e.g. PMID:28743734.

Adding just the number, e.g. 28743734, works, but adding PMID:28743734 fails after the red loading box appears, and automatically logs me out.

Thx.

**Comment by valearna** [comment]
If you put accessions in double quotes (e.g., "PMID:28743734") it works. It seems that special characters outside double quotes are not processed correctly. I'll try to find a way to process special characters, maybe adding extra double quotes when needed.

**Comment by vanaukenk** [comment]
Ah, I didn't think that the ":'" might be the source of the problem.
If there isn't an easy workaround, then maybe this is another good place to put a question mark and examples of what accession formats are accepted.
Would it be possible, if there is an error like this, to get some kind of message that the search failed, but not automatically get logged out?  
Thx @valearna

**Comment by valearna** [comment]
I can definitely add a question mark with some examples, but it will be hard to identify cases when there is an error like this since the search crashes and you get logged out for that reason. The only way to identify the error is to fix it.

**Comment by vanaukenk** [comment]
Okay, thanks for the explanation.

**Comment by valearna** [comment]
The bug has been fixed in the new Textpressocentral version (now online). I also added the question mark with some examples.
