### ISSUE TITLE
Explicit highlighting of matches (keyword(s) and sentence) when using "Scroll through search results" buttons

### ISSUE THREAD

**Issue by chris-grove** [WormBase/textpresso#108]
Enhancement/feature request:

When looking through a paper's content in the "Curation" tab after a search, I can use the "Scroll through search results" buttons to move through the matching sentences in the paper, one at a time. This is good, except that it isn't always clear which sentence has been selected from any given click on the buttons, except that it might be the sentence at the top of the screen. It also isn't immediately apparent as to why the sentence is matched, as I may perform a search on a set of keywords or a phrase, and the sentence matches to one of the words but not all of them. I think it would be helpful to users to highlight (A) the sentence of focus for having clicked on the scroll buttons and (B) the keyword(s) that made that sentence a match.

**Comment by valearna** [comment]
I implemented a new function for point B: The categories and keywords used during the search are now passed to the viewer (Curation tab), and all their occurrences are highlighted separately in the document.

**Comment by chris-grove** [comment]
@valearna 
Nice! I like it!
