### ISSUE TITLE
TPC search reset after 11 "Highlight particular keyword" searches

### ISSUE THREAD

**Issue by chris-grove** [WormBase/textpresso#109]
I found that if I search for papers and then select a paper to view in the "Curation" tab, when I open the Options and enter terms into the "Highlight particular keyword" search and press ENTER, the 11th search always resets the page, making the Curation tab blank and resetting the "Search" tab entirely, making me start my search and annotation over again. Here's a screen recording:

https://www.dropbox.com/s/ci5wp1mx28jwwc4/TPC_reset_after_11_highlight_particular_keyword_searches.mov?dl=0

**Comment by chris-grove** [comment]
Turns out this also happens if you do 11 "Highlight particular labels" search from the drop down list of vocabularies. The two search types appear to count up independently because I can do 10 of each on the same paper without error, but doing the 11th of either will reset TPC search and curation tabs.

**Comment by valearna** [comment]
There was a bug in the function to select highlighting colors. The problem has been solved.

**Comment by chris-grove** [comment]
@valearna 
Looks good! Thanks!
