### ISSUE TITLE
Add Advanced Search options

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#11]
Some of the Advanced Search options on the old site, particularly the ability to restrict searches to a specific year, paper, and journal, are really useful.

It'd be nice to have these options available on the home page for TPC.

--Kimberly

**Comment by vanaukenk** [comment]
As we've just discussed on the call, these filters (author, journal, paper, year) could be added into the main search page.

**Comment by liyuling** [comment]
moved Advanced Search options to main page.
