### ISSUE TITLE
TPC sentence search results do not match all search criteria

### ISSUE THREAD

**Issue by chris-grove** [WormBase/textpresso#110]
I found that performing a multiple category search on a particular paper, with the "ALL categories have to be matched." toggled on, and the search scope set to "Sentence" level, I get sentence matches in the paper that don't appear to apply AND logic to the categories to find only sentences that match all criteria. See the following video:

https://www.dropbox.com/s/sp42bocik0zv80l/TPC_sentences_do_not_match_ALL_search_criteria_11-28-2017.mov?dl=0

The problem is most obvious when I use the options menu to highlight matches to the "tables and figures" category. You can see that the top set of sentences do not have any matches to "tables and figures" terms. I can continue to highlight all categories of my searches and can find several sentences that have only one or two categories matched.

**Comment by valearna** [comment]
There was an error in the code that I introduced in the last release. The AND logic was not applied correctly due to a missing whitespace in the " AND" string used to concatenate categories into the query text. I fixed the problem and the query in the video is now working as expected.

**Comment by chris-grove** [comment]
@valearna 
Great! Looks good!
