### ISSUE TITLE
Switching from Curation tab to Search tab and back to Curation tab removes category highlighting

### ISSUE THREAD

**Issue by chris-grove** [WormBase/textpresso#111]
I don't know if this is intentional or not, but while testing and reporting on #110 I noticed that if I perform a TPC search, then open up a paper in the Curation tab and perform highlighting on a category, if I then click back on the Search tab to view the search criteria, and then click back on the Curation tab, all of the highlighting that I had done is removed. See the movie in #110 , look particularly at 1:30 to 2:15 to see a demo

**Comment by valearna** [comment]
The function to redraw the curation tab with the initial highlighting was called every time the curation page was opened, and therefore all the manual highlighting was removed. Now we keep a status variable with the information of the currently selected paper and do not redraw the page if the selection in the search page does not change.

**Comment by chris-grove** [comment]
@valearna 
OK, works well now. Thanks!
