### ISSUE TITLE
Mark papers that are supplementals as such

### ISSUE THREAD

**Issue by rankishore** [WormBase/textpresso#115]
When you are looking for a paper, sometimes you get several supplementals before you get to the actual paper, and this too you have to find out by expanding the initial title, so it could be several pages and clicks before you can actually find the paper itself.  Wondering if a little icon for a supplemental would solve some of these issues.  Also it would be nice if the paper always came up first and then all the related supplementals?

**Comment by draciti** [comment]
Same experience: e.g. WBPaper00051279

**Comment by goldturtle** [comment]
resolved
