### ISSUE TITLE
Handling WBPapers that are actually books

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#118]
We have some WBPapers that are actually books, rather than individual journal articles.  These have Type 'Book' in postgres and have associated ISBN identifiers.

In TPC, I noticed that a book in my search results has no Title, no Year, and Type 'not available'.

This is not urgent, but it'd be good to take a look at how these WBPapers are processed to see if that information could be populated.

The paper I'm looking at is WBPaper00044880.

Thx.

**Comment by goldturtle** [comment]
transferred to https://github.com/TextpressoDevelopers/textpressocentral/issues/10
