### ISSUE TITLE
Getting security error trying to access TPC on Firefox, Chrome, and Safari

### ISSUE THREAD

**Issue by chris-grove** [WormBase/textpresso#120]
I'm getting "You're connection is not secure/private" error messages when trying to access TPC from

Firefox:

<img width="1061" alt="screenshot 2018-02-19 10 47 18" src="https://user-images.githubusercontent.com/611382/36386158-d0f2abac-1562-11e8-8ef5-d6a4a4328290.png">

Chrome:

<img width="1004" alt="screenshot 2018-02-19 10 48 40" src="https://user-images.githubusercontent.com/611382/36386168-d8900e72-1562-11e8-90b6-de574ac7a415.png">

and Safari:

<img width="973" alt="screenshot 2018-02-19 10 49 08" src="https://user-images.githubusercontent.com/611382/36386172-df9af650-1562-11e8-878a-bc223c82e569.png">

For what it's worth, I'm running the Caltech VPN (Cisco AnyConnect Secure Mobility Client) from home.

**Comment by valearna** [comment]
I tried to generate new ssl certificates with the free service that we are using for TPC (letsencrypt.org), but the problem remained. After a few minutes the old certificates started to work again, so I assume that this was a temporary error from letsencrypt. Everything should be ok now.

**Comment by chris-grove** [comment]
@valearna Looks good! Thanks!
