### ISSUE TITLE
Refreshing search results for a paper

### ISSUE THREAD

**Issue by chris-grove** [WormBase/textpresso#121]
This is related to issue #79 

When I perform a search in TPC for a paper with one set of parameters, look at the paper, then go back to search and change my search parameters, and go back to the paper again, the search highlighting seems to still be reflecting the results of my previous search. Here's a screen capture video demo:

https://www.dropbox.com/s/lhueqwmj4k7q09t/TPC_paper_needs_refreshing_for_second_search_Feb_20_2018.mov?dl=0

The original search results can be cleared by reloading the page and starting the query again from scratch, but it would be nice to be able to just change one or two parameters of the search and have the new results show up when inspecting the paper.

**Comment by valearna** [comment]
I modified the behavior of the interface and now the viewer is reloaded every time the user performs a new search. This covers the use case you described, but you still need to hit the search button again after setting the new parameters to have them highlighted in the viewer.

**Comment by chris-grove** [comment]
@valearna 
Great! Looks good, thanks!
