### ISSUE TITLE
Request for new search and display options

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#129]
These requests/suggestions are from J. Ewbank and would be helpful for fine-tuning TPC searches and results display.  

"Having the possibility to restrict a search to a given field (e.g. title) and being able to rank the different columns in the results (i.e. by journal or year, etc, not just Doc score) would be welcome."

Year is already a sorting option on TPC, but other fields, like Journal, would be useful, too.

**Comment by goldturtle** [comment]
Transferred to https://github.com/TextpressoDevelopers/textpressocentral/issues/4
