### ISSUE TITLE
WBPaper00050421 is unparsed

### ISSUE THREAD

**Issue by chris-grove** [WormBase/textpresso#130]
Was trying to compare TPC phenotype curation to manual and community curation for WBPaper00050421, but TPC doesn't recognize sentences. The words seem to all be jumbled together without spaces or something.

**Comment by goldturtle** [comment]
Ok. Thanks for letting us know.


Michael.

On 1/29/19 2:06 PM, Chris Grove wrote:

Was trying to compare TPC phenotype curation to manual and community curation for WBPaper00050421, but TPC doesn't recognize sentences. The words seem to all be jumbled together without spaces or something.

**Comment by goldturtle** [comment]
transferrred to https://github.com/TextpressoDevelopers/textpressocentral/issues/8
