### ISSUE TITLE
Search not returning results when it should

### ISSUE THREAD

**Issue by draciti** [WormBase/textpresso#19]
If I type 
Single molecule FISH and select Anatomy as category I have no results.

When I use the old textpresso engine I do get results, including papers from the PMC corpus

http://www.ncbi.nlm.nih.gov/pubmed?cmd=retrieve&dopt=AbstractPlus&list_uids=22102824
http://www.ncbi.nlm.nih.gov/pubmed?cmd=retrieve&dopt=AbstractPlus&list_uids=23863485
http://www.ncbi.nlm.nih.gov/pubmed?cmd=retrieve&dopt=AbstractPlus&list_uids=21814493

among others

**Comment by goldturtle** [comment]
This is due to not automatically including all children categories of the therm. Also, categories are being ANDed at the moment. Need fix.
