### ISSUE TITLE
Loading the right paper in the curation tab

### ISSUE THREAD

**Issue by draciti** [WormBase/textpresso#22]
Type AWBL in search -> you get 3 papers as result, click on one-> view in curation tab -> opens the right paper. I go back to the search tab, deselect the selected paper, pick another one, go to the Curation tab. I often still see the first paper selected. It does not happen all the times but often.

**Comment by liyuling** [comment]
When you click on "Curaiton" tab, it will take about 1-2 seconds to load the new papers into the page. The upper right corner will have a  red "loading" sign, which means it's loading. after 1-2 seconds, it will refresh the page with right papers.

**Comment by goldturtle** [comment]
When more than 2 papers are selected, a combo box will show up. This box can be overlooked. Make ist more visible
