### ISSUE TITLE
Color customization

### ISSUE THREAD

**Issue by goldturtle** [WormBase/textpresso#27]
Highlighting colors for viewer and search result should be fully customizable.

**Comment by vanaukenk** [comment]
If the customization isn't available yet, is there anything we can do about the yellow color in the meantime?  That color is still very difficult to read:
![pmid_only_sentence_display](https://cloud.githubusercontent.com/assets/1730534/13399553/02f9fd0e-ded2-11e5-8d90-d8c4ea379fde.png)

**Comment by goldturtle** [comment]
Fixed
