### ISSUE TITLE
Duplicate papers

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#3]
I performed a multiple keyword search using 'his-24 deficient' and got two papers back, but they seem to be duplicates of PMID 23028351.
The first paper returned lists a sentence from the abstract twice, while the second paper lists a sentence from the Introduction once.
Also, in both cases, 'deficient' is shown in red, but 'his-24' is not highlighted in red.

**Comment by liyuling** [comment]
Hi Kimberly,

Thanks for feedback. I tried searching "his-24 deficient" in the keyword box

http://131.215.52.209:9000/

It returned me 77394 results. The top1 result is that paper PMID 23028351. Could you try again?

The coloring issue may be due the hyphen in 'his-24'. I will try to fix it.

Thanks

**Comment by vanaukenk** [comment]
Hi Yuling,

Thanks; I was performing my search using the Search Scope of a sentence - sorry I forgot to mention that in reporting the issue.

When I search using full text for the scope, I get the same result that you do: 77394 results with PMID 23028351 as the top result.

When searching using full text, and looking at the matching sentences, I see 'deficient' highlighted, but not his-24 (as mentioned) and I also see an instance of just  'his' highlighted.  I don't see the just 'his' returned in the sentence scope search.  

How is the search currently set up with respect to exact match criteria? 

Thx.

**Comment by liyuling** [comment]
Hi Kimberly,

Right now, searching and highlighting are two separate steps. Searching is done first(exact match in this case) and then highlighting will try to find those keywords in snippets and highlight them. your case of 'his-24' not being highlighted has been addressed during highlighting step now.
