### ISSUE TITLE
Search scope

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#30]
Default search scope on textpresso.org is 'sentence', but it looks to be 'document' on tpc.

Do you have any data on what people use most?

For curation, I mostly use 'sentence'; would be good if this feature was either customizable, both options showed with a checkbox to make users more aware of the different options, or 'sentence' was default on tpc, as well.

**Comment by liyuling** [comment]
Sure. if curators prefer using 'sentence' level search as default option, we could change that,

**Comment by liyuling** [comment]
"sentence" level search scope is now the default scope. changes will be adopted after next build.
