### ISSUE TITLE
How is doc score calculated?

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#32]
I'm wondering how the doc score is calculated.

When I perform a search on the C. elegans corpus using three categories:

mf enz. activ. assay (tpmfeaa:0000001)
mf enz. activ. verbs (tpmfeav:0000001)
protein (C. elegans) (tppce:0000001)

the paper at the top of the list is WBPaper00013463, followed by four others; all of these papers have a doc score of 1.

On textpresso.org, using the same search criteria, the score for each of these five papers is:
1) WBPaper00013463 - 15
2) WBPaper00035427 - 550
3) WBPaper00041726 - 60
4) WBPaper00003307 - 259
5) WBPaper00035602 - 104

**Comment by liyuling** [comment]
The old Textpresso system ranks the results based on the number of "hits". TextpressoCentral uses "Lucene" search engine core which uses a more sophisticated calculation method, including "TF-IDF" algorithm, which takes more factors into consideration(number of hits, paper length, etc).  In short, we use a more widely used ranking method from Lucene for new system.(hopefully it's better and more reflective of the quality of the hits.)

**Comment by vanaukenk** [comment]
Thanks, Yuling.  This is very interesting.

I checked the SVM classification of those five papers and they classify as:
1) Negative (true negative)
2) High (true positive)
3) n/a (Review)
4) Medium (true postive)
5) High (weak positive, i.e. doesn't have in vitro enzymatic data, but mutant phenotypes)

The sample size here is very small, but this suggests that having an SVM filter and also the option to filter out articles with no primary data would help hone the results.

I tried to flip the search around and do document-specific searches on tpc using the accessions from the highest scoring papers in Textpresso searches, but I couldn't get that to work.  I cut and paste the WBPaper ID in the Accession box on tpc and then pressed Search, but let me know if I'm doing something wrong or if that feature is not working yet.

I'd like to get more numbers for these search results and do more comparisons.  This does have me thinking, though, about whether categories optimized for producing a high Textpresso score will perform as well in tpc.  I'll look at some other searches that I routinely do to see how those results compare.  I'd like to get some sense if this outcome is data type-specific.

Let me know if you have other suggestions or thoughts.

Thx.

**Comment by goldturtle** [comment]
Kimberly writes:
"The sample size here is very small, but this suggests that having an SVM filter and also the option to filter out articles with no primary data would help hone the results."

The SVM filter is still on our agenda, but it will take a while, but the filter for primary data will throw the whole philosophy behind TPC into disarray, as primary-data filter is a very Wormbase-specific filter, while TPC is a platform for all MODs and the biocuration community. I could imagine to implement this in form of a postgres query against an outside-database, where the user can define filters in tables. I just completed the framework for this with the auto-complete functionality in curation form, and can be easily adapted to paper ids, I think.

**Comment by goldturtle** [comment]
Kimberly writes:
"I tried to flip the search around and do document-specific searches on tpc using the accessions from the highest scoring papers in Textpresso searches, but I couldn't get that to work. I cut and paste the WBPaper ID in the Accession box on tpc and then pressed Search, but let me know if I'm doing something wrong or if that feature is not working yet."

This should work. Maybe you can show what you did next week when you are here.

**Comment by goldturtle** [comment]
Kimberly writes:
"I'd like to get more numbers for these search results and do more comparisons. This does have me thinking, though, about whether categories optimized for producing a high Textpresso score will perform as well in tpc. I'll look at some other searches that I routinely do to see how those results compare. I'd like to get some sense if this outcome is data type-specific."

Yes, I think more trial-and-error is needed for this.

**Comment by vanaukenk** [comment]
Michael writes:

"The SVM filter is still on our agenda, but it will take a while, but the filter for primary data will throw the whole philosophy behind TPC into disarray, as primary-data filter is a very Wormbase-specific filter, while TPC is a platform for all MODs and the biocuration community. I could imagine to implement this in form of a postgres query against an outside-database, where the user can define filters in tables. I just completed the framework for this with the auto-complete functionality in curation form, and can be easily adapted to paper ids, I think."

An alternative would be to use the more universal paper type information, like Review, that is assigned during PubMed indexing.  The downside to this is the lag time between when a paper is first submitted to PubMed and when it gets fully indexed.  That was the main reason we implemented the primary/not-primary flag in postgres, so we could flag papers as soon as they came in for appropriate downstream processing.  
There may be other approaches - we could brainstorm.

**Comment by goldturtle** [comment]
We identified during our meeting that scoring for searches on a sentence level is not complete because results for the same paper are not being collected and summed up. This can be fixed by introducing a multimap (C++-specific container) with the paper ID as an index and a list of sentence identified (which probably is identical to the Lucene doc identifier) as values. The map is the used to calculate a score and display all hits properly.

**Comment by liyuling** [comment]
combining sentences from one paper into one entry is implemented. scores are calculated based on collected sentences for each paper, and are normalized.
