### ISSUE TITLE
Perform case-sensitive searches

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#38]
Hi-
Is there a way to perform case-sensitive keyword searches in TPC?

I'd like to distinguish between a gene and a protein, e.g. mut-7 vs MUT-7.

Thx.
--Kimberly

**Comment by liyuling** [comment]
By default, the word analyzer that Lucene index uses is case-insensitive. To make the search case-sensitive, we would need to modify the word analyzer of Lucene. or we could make two indices, for case-sensitive search and case-insensitive search, which might be too space consuming.

**Comment by goldturtle** [comment]
http://stackoverflow.com/questions/2487736/lucene-case-sensitive-insensitive-search

http://www.gossamer-threads.com/lists/lucene/java-user/28207
