### ISSUE TITLE
Display of Accession in search results - duplicates?

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#39]
What determines which paper accession is displayed in the search results?

A keyword search on 'mut-7' lists both WBPaper ID and PMIDs, even though the PMIDs have corresponding WBPaper IDs.

Sometimes the same sentence appears listed under each accession separately, but the sentence actually has a different score depending on the accession.

As an example, a search with 'MUT-7' and the 'mf enz activ assay' and 'mf enz activ verbs' categories lists, as the third and fourth entries, the same sentence with scores of 0.611 and 0.592, respectively, for WBPaper00024699 and PMID 15653635.

Thx.
--Kimberly

**Comment by vanaukenk** [comment]
Duplicate papers are still being returned with searches; one of the entries has all of the relevant IDs, the other only the PMID.  The search scores are different for each entry.

![duplicate_papers](https://cloud.githubusercontent.com/assets/1730534/13397497/3defdfdc-dec8-11e5-87c7-dfca1ff77cda.png)

**Comment by goldturtle** [comment]
This smells like the paper is in the PMCOA corpus as well as the C. 
elegans corpus, but Yuling would need to investigate. As the papers are 
tokenized differently, the score differs.

M.

**Comment by vanaukenk** [comment]
Yes, that makes sense.  When there are duplicates, though, which one should be returned?  Note also that the PMID only papers display formatting when you click on the arrow to see the sentences:
![pmid_only_sentence_display](https://cloud.githubusercontent.com/assets/1730534/13399396/15518fb8-ded1-11e5-87b8-35432dda4789.png)

**Comment by vanaukenk** [comment]
For testing purposes, this is the search that I performed to get these results:
Search scope: sentence
Keywords: DYN-1
Categories (match all): MFEA assay terms
                                     MFEA verbs

**Comment by vanaukenk** [comment]
What is the current status of this issue wrt the C. elegans corpus?  Screenshots of searches of the C. elegans corpus still display duplicate papers.  Did we decide that we would go with the PMCOA version if it existed, and if not, then use the PDF version of the paper?  
Also, a related issue, how do we want to handle supplemental files?  It doesn't look like PMCOA contains the supplemental material, but I don't know if that's universally true.  
When they are available, some labeling of supplemental materials would help indicate where the additional results are from.

**Comment by goldturtle** [comment]
transferred to https://github.com/TextpressoDevelopers/textpressocentral/issues/30
