### ISSUE TITLE
Edit autocomplete and validation button

### ISSUE THREAD

**Issue by draciti** [WormBase/textpresso#43]
In the customization tab
http://sandbox.textpresso.org/cgi-bin/tc/tpc/customization

the Edit autocomplete and validation button acts funny (in Firefox)-see screenshot.
Cannot enlarge/reduce
thanks
![screen shot 2015-12-01 at 11 19 18 am](https://cloud.githubusercontent.com/assets/901243/11511378/a4028ec4-981d-11e5-8031-8971fbc19b55.png)

**Comment by goldturtle** [comment]
It doesn't act funny with me. You need to show this during a google hangout. Kimberly once had some problems because her javascript wasn't updated.
