### ISSUE TITLE
html formatting

### ISSUE THREAD

**Issue by draciti** [WormBase/textpresso#50]
if you select more than one paper in the search page, then go to the curation tab, it says:
'You have selected several papers while searching. Please select one for viewing:'

Click on Select Paper (the text here is cut in half, you might want to reduce the font) and you will see that the text has html formatting

**Comment by draciti** [comment]
![screen shot 2015-12-03 at 12 44 27 pm](https://cloud.githubusercontent.com/assets/901243/11573524/a2c8b142-99bb-11e5-9b28-8f2fd21d7930.png)

**Comment by vanaukenk** [comment]
Looks like this is still an Issue, but perhaps only for those papers that just have a PMID identifier in the accessions field?
![html_formatting_in_list](https://cloud.githubusercontent.com/assets/1730534/13397749/484ca66c-dec9-11e5-82cc-0ad9bfb30f16.png)

**Comment by vanaukenk** [comment]
I have a question about this functionality, in general, though.  If the user can select multiple papers from the search page, but then has to choose only one paper from this next page for viewing, is there a reason they aren't instructed just to choose one paper from the beginning?  
My expectation from being able to select multiple boxes from the search page is that I would be able to scroll through multiple papers with the next action, 'View in Curation tab'.

**Comment by goldturtle** [comment]
The selection column in the search page will be used for more than just 
choosing papers to view, i.e., for saving lists later on. Also, there is 
no real estate in the viewer to display more than one paper in the 
viewer. You can switch from one paper to the other in the viewer by 
selecting the other paper in the popup menu without having to go back to 
the search interface.

**Comment by goldturtle** [comment]
Obsolete. Can only pick one paper now. Will address issue of lists later.
