### ISSUE TITLE
able to generate validated lists

### ISSUE THREAD

**Issue by draciti** [WormBase/textpresso#52]
we should be able to add tems by double clicking on them and they will be stored as validated lists, as it happens in OA

**Comment by goldturtle** [comment]
done

**Comment by draciti** [comment]
michael could you please leave the tickets open until we are able to test?

**Comment by draciti** [comment]
in which field type did you implemented it?
http://sandbox.textpresso.org/cgi-bin/tc/tpc/customization
![screen shot 2015-12-15 at 2 19 07 pm](https://cloud.githubusercontent.com/assets/901243/11825925/ebd29266-a336-11e5-9834-e6c0bafef02b.png)

just to recap the goal is to
- be able to generate a field (say expressed_in) available in the curation panel
- while reading the paper -> double clicking on anatomy terms will insert the anatomy terms in the expressed_in field, making sure they are valid ontology terms.

You might have implemented it but I cannot reproduce. thanks

**Comment by goldturtle** [comment]
You need to use the listmaker option when creating a field.

M.

**Comment by draciti** [comment]
thanks, I have seen you have added a 'list maker' field
![screen shot 2016-01-05 at 11 15 48 am](https://cloud.githubusercontent.com/assets/901243/12125058/ef630fa6-b39d-11e5-9f9e-167897a436fe.png)

I have tried to use the functionality by selecting it and trying to double click on anatomy terms to populate the fields (while being on the curation tab) but is not as I was expecting. I will talk to other curators and then we can talk on google hangouts

**Comment by goldturtle** [comment]
I have tested the listmaker functionality on sandbox with click'n fill. 
It generally works for me, however, there is an issue with a trailing 
space that is always transferred to the line edit and prevents the 
validator to find the correct entry. If I remove the trailing space, the 
validator validates. Would that explain it? I can remove trailing and 
leading spaces programmatically.

M.
