### ISSUE TITLE
postgres communication

### ISSUE THREAD

**Issue by draciti** [WormBase/textpresso#53]
first URL
http://sandbox.textpresso.org/cgi-bin/tc/tpc/curation

this gives you a pgid 
then you send to a second URL

second URL
?action=updatePostgresTableField&pgid=' . $pgid . '&field=' . $field . '&newValue=' . $data . '&datatype=' . $datatype . '&curator_two=' . $curator

**Comment by goldturtle** [comment]
This is not the way it's going to be working. We should reduce the number of communication per session in case the system gets heavily used. Instead you should get an authentication token from your pg administrator that is permanent (or is changed on a periodic basis) that you submit together with all other data in _one_ submission to pg.

**Comment by draciti** [comment]
I would leave the ticket open until we have a working plan. For some reason it does not let me. Please reopen
