### ISSUE TITLE
Recognition of inferred ontology terms in Textpresso Central

### ISSUE THREAD

**Issue by chris-grove** [WormBase/textpresso#55]
Right now, when performing a search using categories in TPC, the search does not recognize terms that are descendants of the terms selected. So selecting the category "C. elegans Cell and Anatomy Ontology (WBbt:0000100)" and specifying the paper under "Additional Search Options" as WBPaper00041930 returns zero results, whereas searching for the descendant term "pharynx (WBbt:0003681)" or just the string "pharynx" finds a couple of hits for the paper WBPaper00041930.

**Comment by draciti** [comment]
hey Chris, I raised this issue a while ago. Michael suggested to add a children checkbox in the pick categories pop up window, ticket #42. FYI. I will merge ticket #42 with this one

**Comment by chris-grove** [comment]
@draciti  OK sounds good, thanks.
