### ISSUE TITLE
remember customization

### ISSUE THREAD

**Issue by draciti** [WormBase/textpresso#56]
It seems that if I select only C elegans literature in the customization tab, the system does not recognize it in future sessions. Is this supposed to be the case?
http://sandbox.textpresso.org/cgi-bin/tc/tpc/customization
![screen shot 2016-01-06 at 9 11 34 am](https://cloud.githubusercontent.com/assets/901243/12148844/86fe9c42-b455-11e5-9ad3-6455b433f689.png)

On a related note, it would be good to have the Check/Uncheck all literature button checked by default, to avoid an extra click.

**Comment by goldturtle** [comment]
I am removing a bug that might be related to that. The check/uncheck all literature button is there, even in your screen shot. 

M

Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by draciti** [comment]
yes, I know it's there.. I was asking if it could be checked by default, otherwise to select just elegans one should have an extra click
