### ISSUE TITLE
Think about how to organize the category list

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#59]
We should think about how best to organize the category list so that users can more easily see what is available to them.
One idea is a top-level list like this (alphabetized):
Alleles and Variations
Anatomy and Cell Types
Basic Formal Ontology (BFO)
CHEBI
Gene Ontology (GO)
Genes and Proteins
Human Disease
Life Stages
Phenotype and Trait Ontology (PATO)
Sequence Ontology (SO)

That would then open up to the more extensive list of category options.

Also, is it necessary for the user to see the parenthetical ID after the category name?

**Comment by vanaukenk** [comment]
I think this issue is central to users having a good, intuitive search experience at TPC.  There is too much buried under the customized ontology list and having the different branches of ontologies like ChEBI spread out makes it harder for people to appreciate everything that is available for searching. 
Also, then when we need to add more ontologies or vocabularies, e.g. Drosophila gene names or zebrafish phenotypes, those new categories have a logical place to go. 

Here's a suggested re-organization of the list similar to what I posted above but with more detail.  Each of the headings farthest to the left would be the starting point for browsing.   I think something along these lines would make it easier for users, especially non-curators, to browse and effectively use the TPC categories.

Alleles and Variations
    allele (C. elegans)
    Variation (C. elegans)
Anatomy and Cells
    anatomical structure
    C. elegans Cell and Anatomy Ontology
Basic Formal Ontology (BFO)
    material entity
    quality
Chemicals and Molecules
    chemical entity (ChEBI)
    Molecules (uncategorized)
    role (ChEBI)
    subatomic particle (ChEBI)
Disease
    human disease
Gene Ontology (GO)
    biological_process
    cellular_component
    molecular_function
Gene Ontology Curation 
    Cellular Component (CC)
        Localization assay terms
        Localization cellular components
        Localization verbs
    Molecular Function
        Molecular Function Enzymatic Activity (MFEA)
            MFEA assay terms
            MFEA verbs
        Molecular Function Physical Interactions (MFINT)
            MFINT assay terms
            MFINT verbs
Genes and Proteins
    Gene (C. elegans)
    Protein (C. elegans)
Genetics
    genetic interaction (WormBase curation)
    genetic perturbation (WormBase curation)
    phenotypic perturbation (WormBase curation)
    Variant
Life Stages
    Nematoda Life Stage
Phenotype and Trait Ontology (PATO)
    quality
Sequence Ontology (SO)
    sequence_attribute
    sequence_collection
    sequence_feature
    sequence_variant

**Comment by vanaukenk** [comment]
Ah, the structure didn't come through, so I will add it again with dashes.  Stay tuned....

**Comment by vanaukenk** [comment]
Alleles and Variations
-allele (C. elegans)
-Variation (C. elegans)
Anatomy and Cells
-anatomical structure
-C. elegans Cell and Anatomy Ontology
Basic Formal Ontology (BFO)
-material entity
-quality
Chemicals and Molecules
-chemical entity (ChEBI)
-Molecules (uncategorized)
-role (ChEBI)
-subatomic particle (ChEBI)
Disease
-human disease
Gene Ontology (GO)
-biological_process
-cellular_component
-molecular_function
Gene Ontology Curation 
-Cellular Component (CC)
--Localization assay terms
--Localization cellular components
--Localization verbs
-Molecular Function
--Molecular Function Enzymatic Activity (MFEA)
---MFEA assay terms
---MFEA verbs
--Molecular Function Physical Interactions (MFINT)
---MFINT assay terms
---MFINT verbs
Genes and Proteins
-Gene (C. elegans)
-Protein (C. elegans)
Genetics
-genetic interaction (WormBase curation)
-genetic perturbation (WormBase curation)
-phenotypic perturbation (WormBase curation)
-Variant
Life Stages
-Nematoda Life Stage
Phenotype and Trait Ontology (PATO)
-quality
Sequence Ontology (SO)
-sequence_attribute
-sequence_collection
-sequence_feature
-sequence_variant

**Comment by goldturtle** [comment]
OK, thanks. I'll be working on this, but it will take some time. 
Anything related to categories have a longer turn-over time, as there is 
a lot of manual editing of obo-files (the sources for the lexica) 
required. Once the lexica are ready, everything needs to be marked up an 
indexed anew.

Michael.

On 07/07/2016 10:43 AM, vanaukenk wrote:

> Alleles and Variations
> -allele (C. elegans)
> -Variation (C. elegans)
> Anatomy and Cells
> -anatomical structure
> -C. elegans Cell and Anatomy Ontology
> Basic Formal Ontology (BFO)
> -material entity
> -quality
> Chemicals and Molecules
> -chemical entity (ChEBI)
> -Molecules (uncategorized)
> -role (ChEBI)
> -subatomic particle (ChEBI)
> Disease
> -human disease
> Gene Ontology (GO)
> -biological_process
> -cellular_component
> -molecular_function
> Gene Ontology Curation
> -Cellular Component (CC)
> --Localization assay terms
> --Localization cellular components
> --Localization verbs
> -Molecular Function
> --Molecular Function Enzymatic Activity (MFEA)
> ---MFEA assay terms
> ---MFEA verbs
> --Molecular Function Physical Interactions (MFINT)
> ---MFINT assay terms
> ---MFINT verbs
> Genes and Proteins
> -Gene (C. elegans)
> -Protein (C. elegans)
> Genetics
> -genetic interaction (WormBase curation)
> -genetic perturbation (WormBase curation)
> -phenotypic perturbation (WormBase curation)
> -Variant
> Life Stages
> -Nematoda Life Stage
> Phenotype and Trait Ontology (PATO)
> -quality
> Sequence Ontology (SO)
> -sequence_attribute
> -sequence_collection
> -sequence_feature
> -sequence_variant
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/WormBase/textpresso/issues/59#issuecomment-231153595, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AIPBGyA6jdYDQ1qZHfRmPCXdpNFPHYTfks5qTTrSgaJpZM4HlhT8.

## 

Hans-Michael Muller, PhD
Scientific Analysis
M/C 156-29
California Institute of Technology
Pasadena, Ca 91125

**Comment by goldturtle** [comment]
Hi Kimberly,

I will be working on re-organizing the category menu/hierarchy soon. As 
this involves a somewhat extensive manipulation of obofiles, changes 
will not occur frequently. Thus, this is your last chance to modify the 
list and structure for a while.

Michael.

On 07/07/2016 10:43 AM, vanaukenk wrote:

> Alleles and Variations
> -allele (C. elegans)
> -Variation (C. elegans)
> Anatomy and Cells
> -anatomical structure
> -C. elegans Cell and Anatomy Ontology
> Basic Formal Ontology (BFO)
> -material entity
> -quality
> Chemicals and Molecules
> -chemical entity (ChEBI)
> -Molecules (uncategorized)
> -role (ChEBI)
> -subatomic particle (ChEBI)
> Disease
> -human disease
> Gene Ontology (GO)
> -biological_process
> -cellular_component
> -molecular_function
> Gene Ontology Curation
> -Cellular Component (CC)
> --Localization assay terms
> --Localization cellular components
> --Localization verbs
> -Molecular Function
> --Molecular Function Enzymatic Activity (MFEA)
> ---MFEA assay terms
> ---MFEA verbs
> --Molecular Function Physical Interactions (MFINT)
> ---MFINT assay terms
> ---MFINT verbs
> Genes and Proteins
> -Gene (C. elegans)
> -Protein (C. elegans)
> Genetics
> -genetic interaction (WormBase curation)
> -genetic perturbation (WormBase curation)
> -phenotypic perturbation (WormBase curation)
> -Variant
> Life Stages
> -Nematoda Life Stage
> Phenotype and Trait Ontology (PATO)
> -quality
> Sequence Ontology (SO)
> -sequence_attribute
> -sequence_collection
> -sequence_feature
> -sequence_variant
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/WormBase/textpresso/issues/59#issuecomment-231153595, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AIPBGyA6jdYDQ1qZHfRmPCXdpNFPHYTfks5qTTrSgaJpZM4HlhT8.

## 

Hans-Michael Muller, PhD
Scientific Analysis
Member of the Professional Staff
M/C 156-29
California Institute of Technology
Pasadena, Ca 91125

**Comment by vanaukenk** [comment]
@goldturtle - this seems to be done.  Shall we close the ticket?
