### ISSUE TITLE
Move information about search results to top of the page

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#60]
One of the nice features about the old Textpresso is that the number of matches and the number of documents, as well as the total number of pages is listed at the top of the search results.  
This helps users to immediately get a sense of whether their search was too narrow/too broad.
Can this information be moved/added to the top of the TPC search results page?
Also, we should be clear on what 'Results' means.  Matching sentences?  Matching documents?
![search_results_top_of_page](https://cloud.githubusercontent.com/assets/1730534/13399799/087136a2-ded3-11e5-9d1a-f42cf912fd24.png)

**Comment by vanaukenk** [comment]
I think this one is critical to fix.  One of the things users want to know immediately when they perform a search is whether or not their search criteria was specific enough and the number of 'hits' returned helps inform that.
Also, if Results = Papers we should say that, and the total number of pages, plus where the user is on the list of pages, should be clear, i.e. Page 2 of 35.
Basically, this aspect of search return behavior should look like PubMed.

[PubMed_Search_Results.pptx](https://github.com/WormBase/textpresso/files/341992/PubMed_Search_Results.pptx)

**Comment by goldturtle** [comment]
This has been adjusted now. # of documents where matches have been found is now shown on the top left, page info (page a of b) in the bottom left. In case of sentence level searches, # of sentences is displayed too.
One curious thing occurs when comparing a query on document level with one on sentence level. I do get a slightly different number of documents when searching for a keyword, for example. I would have expected the same number. I am not sure where the inconsistency occurs, when calling Lucene routines or during the combining of sentences to documents. Yuling would need to shine some light on this. If it happens on the Lucene level, we can't do anything about it.
