### ISSUE TITLE
Add 'tables and figures' category to TPC

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#61]
The 'tables and figures' category in the Description section of old Textpresso is very useful for honing search results to experimental findings.
Can we add that to TPC?

**Comment by vanaukenk** [comment]
This has been added, but is listed under 'customized ontology'.  I think it'd be easier to find if it was just listed separately as 'tables and figures'.

**Comment by goldturtle** [comment]
transferred to https://github.com/TextpressoDevelopers/textpressocentral/issues/28
