### ISSUE TITLE
Display of accessions - formatting

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#62]
When there are multiple accessions for a paper, it would be helpful to have clearer formatting.  Currently, we have things like this:

Other:doi10.1091\/mbc.E09-05-0440 PMID:20016007 
WBPaper00035546

Perhaps one accession per line would help, with PMID, probably the most widely used, first:
PMID:20016007
doi:10.1091/mbc.E09-05-0440
WBPaper00035546

Note also that I removed the 'Other' from the doi listing, added a colon between 'doi' and the identifier, and removed the forward slash.

**Comment by vanaukenk** [comment]
Note that the forward slash also shows up in the display of paper titles:

![search_results_top_of_page](https://cloud.githubusercontent.com/assets/1730534/13400319/2f24a50c-ded5-11e5-8117-83ddc65f6de8.png)

Note the third title from the bottom.

**Comment by goldturtle** [comment]
I have dealt with the doi: issue. It will be visible on the website next time we index the C. elegans corpus again.
Yuling: If Kimberly wants one identifier per line, then setting the WordWrap flag might not be enough (you would need to try this out). You probably need to separate and display them with a Wt::WBreak() in between them,

**Comment by liyuling** [comment]
OK, I will try. My guess is separating them and then assembling them would be essential.

**Comment by goldturtle** [comment]
Seems to be resolved
