### ISSUE TITLE
loading in specific papers

### ISSUE THREAD

**Issue by kyook** [WormBase/textpresso#7]
Would it be possible to load in a pre-filtered corpus of papers?  Not sure if this was already discussed, but it would be helpful for curation to be able to work on the papers already flagged for a datatype.

**Comment by vanaukenk** [comment]
I second this.  It would be really useful to be able to filter search results based on a specific SVM classification.

**Comment by goldturtle** [comment]
Implementing SVM which enables users to prefilter according to datatype is on our to-do list.
