### ISSUE TITLE
Comparing results between old and new Textpresso

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#70]
Hi,

I'm trying to understand the difference between search results on old vs new Textpresso.  

The search criteria are:
Keywords: adenylate cyclase (old)
Keywords: adenylate AND cyclase (new)
Category: Protein (C. elegans)

The most relevant paper returned is the same for both sites and is WBPaper00034747.

However, old Textpresso returns 18 matching sentences while TPC returns 4.  All four sentence returned by TPC are also returned by old Textpresso.

I can't figure out what causes the difference.  Am I doing something wrong or not making the correct comparison?

Thx.
--Kimberly

**Comment by liyuling** [comment]
Thanks for feedback. I will look into it. I guess it might a bug.

**Comment by liyuling** [comment]
The bug has been identified as lack of delimiters in Category indexer. And a fix has been added into code base. We hope next round markup will have this bug fixed.

**Comment by liyuling** [comment]
The 18 matching sentences from TPC in the example paper now match the old Textpresso results. But the highlighting for some category hits were off some positions. I will fix this in highlighting process. The indexer and searcher should be fine.

**Comment by liyuling** [comment]
The highlighting issue has been fixed as well.  This ticket's bug has been fixed at code level, up to my knowledge.

**Comment by goldturtle** [comment]
The new C. elegans index is now online on sandbox. 19 matches show up 
for Kimberly's query, as in the old T 2.5 system. C. elegans 
supplementals probably follow tomorrow, then other corpora.

M.

On 05/31/2016 06:44 PM, liyuling wrote:

> The 18 matching sentences from TPC in the example paper now match the 
> old Textpresso results. But the highlighting for some category hits 
> were off some positions. I will fix this in highlighting process. The 
> indexer and searcher should be fine.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/WormBase/textpresso/issues/70#issuecomment-222870634, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AIPBG6egNXsSlJ03uUPDqaa36Rq5hjTfks5qHOQDgaJpZM4Im32o.

## 

Hans-Michael Muller, PhD
Scientific Analysis
M/C 156-29
California Institute of Technology
Pasadena, Ca 91125
