### ISSUE TITLE
Advanced search option to filter by year not inclusive enough

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#71]
The Advanced Search Option to filter by year only seems to be working if the year is the only component of the publication date for a paper.

For example, filtering on 2012 seems to work for papers that have Year: 2012, but not for papers that have Year: 2012-10-23.

**Comment by liyuling** [comment]
I noticed that, that's due to papers coming from different sources, so the bib-format is different. either we need to process the  "year" before it enters our paper repository or we process the "year" before indexing it...

**Comment by goldturtle** [comment]
Another option is to make the user use wildcards in the filter 
interface, i.e., typing in 2012*, or add the wild card automatically for 
the year filter.

M.

On 07/06/2016 12:09 AM, liyuling wrote:

> I noticed that, that's due to papers coming from different sources, so 
> the bib-format is different. either we need to process the "year" 
> before it enters our paper repository or we process the "year" before 
> indexing it...
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/WormBase/textpresso/issues/71#issuecomment-230695341, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AIPBG8HKZqT6HiUW6BNqZpW71NVvrWXtks5qS1SsgaJpZM4JFk-e.

## 

Hans-Michael Muller, PhD
Scientific Analysis
M/C 156-29
California Institute of Technology
Pasadena, Ca 91125

**Comment by liyuling** [comment]
or backend could add the wildcard "*" by itself, for 4-digit year from user.

**Comment by vanaukenk** [comment]
Might be worth taking a step back and thinking about what users would most want here.   I suspect that users really want to sort by Publication Date.
In that case, would it be possible to sort entries according to most-to-least granular dates?  Something like this:
2012-12-12
2012-11
2012
and so on.

**Comment by goldturtle** [comment]
But this is now a sorting issue, and not a filtering. We'll see how 
Yuling implemented it.

M.

On 07/06/2016 08:00 AM, vanaukenk wrote:

> Might be worth taking a step back and thinking about what users would 
> most want here. I suspect that users really want to sort by 
> Publication Date.
> In that case, would it be possible to sort entries according to 
> most-to-least granular dates? Something like this:
> 2012-12-12
> 2012-11
> 2012
> and so on.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> https://github.com/WormBase/textpresso/issues/71#issuecomment-230799480, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AIPBGy3YhotrjTBV9WfAikE1xwFAu0nMks5qS8L-gaJpZM4JFk-e.

## 

Hans-Michael Muller, PhD
Scientific Analysis
M/C 156-29
California Institute of Technology
Pasadena, Ca 91125

**Comment by vanaukenk** [comment]
Oh yes, sorry, I'm conflating two things here.  Let's see how the filter by year works first.

**Comment by goldturtle** [comment]
Filtering with wildcard seems to work.
