### ISSUE TITLE
Nematoda Life Stage Category - Term Names not Optimal for Searching

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#72]
Hi,
I've been systematically testing each of the categories in the TPC list and the Nematoda Life Stage category returned many fewer hits than expected.
I suspect that this is due to the term names having 'Ce' at the end, e.g. embryo Ce, as this does not reflect how these terms are written in papers.
Possible solutions?
     1. Have the Nematoda Life Stage ontology include terms like 'embryo' as broad synonyms and then have the TPC search use both term names and synonyms.
     2. Strip the Ce (or Bma or any other appendage) from the term names when using the ontology as a TPC category.
     3. Others?
Solution 1 seems like a more generally useful solution, but maybe there are other, better ideas.

**Comment by goldturtle** [comment]
This category originates from Raymond's WBBT terms/ontology. I'd like to 
keep it as is as those published ontologies are better known/branded, so 
when people stumble upon them on our site, they know what they are 
dealing with. However, I would be happy to introduce a Textpresso 
nematode life stage category that supplements the existing one. Just 
send a list of terms.

Michael.

**Comment by draciti** [comment]
I agree with Kimberly that the best solution will be to include terms like 'embryo' as broad synonyms. It seems the most generalized and stable way of doing it.
Before moving forward I will consult with Jane Lomax and see if she has other ideas.

**Comment by janelomax** [comment]
Hello

In the live Life Stage ontology I've actually replaced Bma with just 'Brugia' for clarity. There are also some additional taxonomic groupings like 'Strongyloides' and 'Platyhelmith'. The EBI's OLS displays a browser with the latest version from GitHub if you want to have a look:

http://www.ebi.ac.uk/ols/ontologies/wbls

But yes, I agree, adding broad synonyms for the the generic 'embryo' or whatever is probably the best solution. That way other users can also get the benefit of these synonyms too.

I can go ahead and add them for the non-elegans species if everyone is happy with that solution?

**Comment by draciti** [comment]
I am Jane, thanks. I will work on adding synonyms for the elegans terms. Leaving this ticket open until the searches are working properly. Thanks Kimberly for your testing

**Comment by janelomax** [comment]
I’ve just committed the parasite synonyms to the Git repo.

I didn’t add them for the very generic stages like ‘life-stage’, ‘adult’, ‘egg’ and ‘embryo’ because I thought these synonyms would probably be too broad to be useful for the text-mining.

**Comment by draciti** [comment]
I have added synonyms for the elegans terms but did not commit on git.
Jane, we briefly discussed at the textpresso meeting that it would be useful for the searches to have a BROAD synonym also for the parasitic very generic terms. Would you mind adding them to the file I sent you via e-mail and then commit? Many thanks,
Daniela

**Comment by janelomax** [comment]
Done!

**Comment by draciti** [comment]
Awesome Jane, thanks!
