### ISSUE TITLE
Display of .ppm figures

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#73]
Hi,
I am test viewing and annotating WBPaper00041607 and the images are hyperlinked paths like this:
images/C. elegans/WBPaper00041607/WBPaper00041607.tpcas.4.ppm
and don't appear to be displaying.

Alternatively, WBPaper00040565 has a mixture of .jpg and .ppm and it looks like the .jpg files display but the .ppm files do not.

**Comment by goldturtle** [comment]
Yep, I am aware of this problem. Probably need to convert ppms into 
other formats.

M.

On 07/07/2016 12:32 PM, vanaukenk wrote:

> Hi,
> I am test viewing and annotating WBPaper00041607 and the images are 
> hyperlinked paths like this:
> images/C. elegans/WBPaper00041607/WBPaper00041607.tpcas.4.ppm
> and don't appear to be displaying.
> 
> Alternatively, WBPaper00040565 has a mixture of .jpg and .ppm and it 
> looks like the .jpg files display but the .ppm files do not.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/WormBase/textpresso/issues/73, or mute the thread 
> https://github.com/notifications/unsubscribe/AIPBGyXM7H41oN2R0DerzeOyKMnF1U8Oks5qTVQ4gaJpZM4JHa-D.

## 

Hans-Michael Muller, PhD
Scientific Analysis
M/C 156-29
California Institute of Technology
Pasadena, Ca 91125

**Comment by goldturtle** [comment]
transferred to https://github.com/TextpressoDevelopers/textpressocentral/issues/24
