### ISSUE TITLE
Exact matches for searches

### ISSUE THREAD

**Issue by goldturtle** [WormBase/textpresso#75]
Kimberly says: Would be nice to be able to perform an exact match filter here.  For example, restricting the SKN-1 search above to Cell Metabol returns all journals whose name contains either of those terms, when I really want just those published in Cell Metabol.

**Comment by valearna** [comment]
Using double quotes in searches could give more accurate results. For example, if you put the journal title in double quotes (e.g., "Cell Metabol"), the whole title is interpreted as a single term, and you get all the journals containing "Cell Metabol" in their title. However, this is not an exact match, as titles such as "Cell Metabol Biol" or "Biol Cell Metabol" would match the query. If using double quotes is not enough, I can add a checkbox in the "additional search options" form to require exact matches and filter out results which contain extra terms.

**Comment by vanaukenk** [comment]
Thanks @valearna 
It would be best to have a checkbox for Exact Match as an additional search option.  This is one of the features in the old Textpresso system that I definitely used.
