### ISSUE TITLE
Scrolling behavior in paper viewer

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#77]
When there are multiple matching sentences for a paper, it looks like the scrolling consistently takes me to the second matching sentence first.

Also, once I click on the scroll arrow, the entire page is getting shifted down so that I no longer see the scroll arrows and just see the very bottom of the scroll arrow boxes.

**Comment by goldturtle** [comment]
Are you talking about the paper viewer?

________________________________

**Comment by goldturtle** [comment]
OK, I can confirm the first issue, but it only happens if you selected multiple papers for viewing. Is that correct?

I can't figure out the second issue as it doesn't happen to me. Maybe another google hangout tomorrow?

**Comment by goldturtle** [comment]
The first issue should be resolved now. I cannot reproduce the second issue.

**Comment by vanaukenk** [comment]
The second issue may possibly be browser-dependent.  I usually use Firefox and I still observe the behavior there, but not when I just tested this on Chrome.
There are also a few other little things that behave differently on Firefox vs Chrome, e.g. the bottom of paper titles in the drop-down list for selecting a paper in the viewer are cut off in Firefox, while they are fully visible in Chrome.

**Comment by goldturtle** [comment]
I test tpc on Firefox and Chrome. The only difference between your and my setting is that you use a Mac and I use Linux.

**Comment by goldturtle** [comment]
@vanaukenk, Is this still an issue?
