### ISSUE TITLE
Clearing a paper's query results

### ISSUE THREAD

**Issue by chris-grove** [WormBase/textpresso#79]
When querying for a paper and getting some initial results, it would be great if there was a way to clear the search result history so that I could redo a query from scratch and see the new search results. As far as I can tell right now, the initial search results stay with the paper in the curation panel, even though a duplicate copy of the paper is presented in the drop-down selection for papers in the Curation tab. Here's a movie demonstrating the existing behavior:

https://www.dropbox.com/s/y45e11eqsdy29v9/TPC_paper_query_movie_9-13-2016.mov?dl=0

**Comment by goldturtle** [comment]
Fixed.
