### ISSUE TITLE
Add ability to select specific values for a field when multiple values are available

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#82]
In some cases, like paper accessions, TPC stores multiple values, e.g. doi, PMID, WBPaper ID.

We will need to have the ability to select specific IDs for specific curation forms so that curators could select, for example, only the PMID to show in the curation form and be sent to an external database.

**Comment by goldturtle** [comment]
transferred to https://github.com/TextpressoDevelopers/textpressocentral/issues/21
