### ISSUE TITLE
"data not shown/unpublished" -automated alert for incoming papers

### ISSUE THREAD

**Issue by draciti** [WormBase/textpresso#84]
Hi Michael, 
would it be possible to set up an automated alert for incoming papers that contain the words ‘unpublished’ and/or ‘Data not shown’?

The automated alert should notify Karen and I via e-mail.
Many thanks
Daniela

**Comment by draciti** [comment]
Hi Micheal, just checking in about the data not shown alerts.
let me know if you need anything from my end.
thanks!

**Comment by goldturtle** [comment]
It's not going to be implemented for a while in TPC. The C. elegans pipeline is not set up yet. If you need results now, ask Juancarlos to set up cronjobs with the scripts he used for the grant. It's based on the old system.

(BTW: this github tracker was meant to be used for TPC, not Textpresso in general.)

**Comment by goldturtle** [comment]
I have been working on this in the last few days, and a sample output can be found at

http://tpc.textpresso.org/curators/daniela/sample.txt

Please focus on the output format rather than the content (I only used a sub C. elegans corpus I have on my laptop) and tell me whether this is what you want,

**Comment by draciti** [comment]
yes, that looks good to me. 
Can the output have the 'unpublished' or 'data not shown' in bold or a different color?
We would want to have an e-mail notification (to draciti@caltech.edu and karen@wormbase.org) for new incoming papers.
Before moving forward let's wait to see if Karen has anything to add.
Thanks

**Comment by kyook** [comment]
I agree with Daniela about the emboldened 'data not shown' and unpublished. I would also add the WBPaperID to that list. 

Would you also pull out e-mail addresses?

**Comment by goldturtle** [comment]
Re:Pulling out e-mail addresses.
I can put that on the to-do list, but it'll take a while.
