### ISSUE TITLE
Local installation on ubuntu not working

### ISSUE THREAD

**Issue by gmadevs** [WormBase/textpresso#85]
I'm trying to run textpresso on an ubuntu 14 system. I used all the default settings but I keep having this error "/cgi-bin/textpresso/home was not found on this server.". I tried changing several subdirectoreis but I can't fix this error. Is there a tutorial somewhere where I can read the settings for a local installation?

**Comment by goldturtle** [comment]
Can you show me the contents of your /usr/lib/cgi-bin directory? That's where apache usually expects cgi-scripts on a Ubuntu system.

**Comment by gmadevs** [comment]
I think I solved the issue, it was a problem with the cgi-bin directory and perl configuration. Thank you
