### ISSUE TITLE
Display of symbols and punctuation in search results

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#89]
Sometimes, the punctuation is not displayed correctly in search results.  

For an example,  search with:

BRCA1 AND variant (keywords)
cateogory: biological_region (SO:0001411) (incl. children)

and look at the sentences returned for the first paper.

For this sample sentence, the display in the viewer is correct:

The BRCA1 c.5074+1G>T variant was reported to result in retention of 150 bp of intron 17.

But in the search results the sentence looks like this:

The BRCA1 c 5074+1G&gt T variant was reported to result in retention of 150 bp of intron 17

**Comment by goldturtle** [comment]
transferred to https://github.com/TextpressoDevelopers/textpressocentral/issues/18
