### ISSUE TITLE
Multiple category searches

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#9]
For multiple category searches it would actually be faster if the user could choose all categories from the same pop-up window, as opposed to having to select each category one at a time via the Add a Category button.

Also, as users select categories, it would be nice to be able to see what you've already selected, either in the pop-up window or on the main search page.

Thx.
--Kimberly

**Comment by goldturtle** [comment]
You can select several categories at once by either using the shift or ctrl key while clicking on categories. Also, one could make use of the checkbox in the popup windows.

You can see selected categories once you picked them on the main search page, and if there are too many, click or "...and more." to trigger a popup window.

**Comment by goldturtle** [comment]
I have redesigned the 'Pick Category' popup window. Let me know how it works for you now.

**Comment by vanaukenk** [comment]
Thanks; I can select multiple categories now.

One thing I like about the old site, though, is that as I'm selecting categories I can immediately see what I've selected as the category box fills in and then when I want to pick another category, I can still see everything that I selected previously.

In the new pop-up window, the category names are at the top of the box and I have to scroll up to the top of the window each time I want to see what I've selected previously.

Would be nice to be able to see everything you've selected while searching for more categories.

Maybe I am still doing it wrong?

**Comment by goldturtle** [comment]
I am kind of not inclined to have another popup window showing the selected categories. It's getting too messy. Let me work on another solution before I give in to popup window fireworks.

**Comment by vanaukenk** [comment]
Thx.
Just thinking out loud...can you control where the Category Popup Window opens up on the page?  If it opened up to the left of the page and then the selected categories appeared on the main page as you selected them, that would have the desired effect.  Don't know what's technically feasible, though.

**Comment by goldturtle** [comment]
OK, a new version it out.
