### ISSUE TITLE
Hide initial display of long sentences in search results

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#91]
Background:  In the old Textpresso system, when a sentence score is above a certain threshold (I don't recall exactly what that threshold score is), rather than display the sentence, the search results display:

Match: [Sentence(s) appears to be scrambled. Click to see (opens new window)] [Field: acknowledgments, subscore: 44.00]

This hides long, often false positive, results but still has the advantage of letting the user look at the results, if they want.

It would be nice to have a similar display in Textpresso Central, although I don't know if sentence score is the appropriate measure for determining which sentences should say this in the search results.

For example, if I perform a search in Textpresso Central as shown in this screenshot, some of the low-scoring sentences that are returned are actually the likely false positives.  Perhaps something like a character count threshold would work?

<img width="1354" alt="search_criteria_false_positives" src="https://cloud.githubusercontent.com/assets/1730534/26605298/73f13cca-455b-11e7-8747-33ebf95727a7.png">

<img width="1357" alt="search_results_false_positives" src="https://cloud.githubusercontent.com/assets/1730534/26605299/73f273ec-455b-11e7-9536-9ff2f3329e86.png">

Thx.

**Comment by valearna** [comment]
Long sentences are now limited to 50 words and marked with a "[Long Sentence]" label. To see the full sentence, you can click on the "show more..." button at the end of the truncated text.

**Comment by vanaukenk** [comment]
Thanks @valearna  That definitely helps.

I don't know if users will want some additional explanation about how we're deciding on what is a long sentence.  Perhaps we could also add a '?' next to the 'Long Sentence' label and then explain, in a pop-up window, how and why they're given that designation?

We have a '?' next to a few other features of the tool and it seems a nice way to add info.
