### ISSUE TITLE
Need a clear notification that login is required to perform search in TPC

### ISSUE THREAD

**Issue by chris-grove** [WormBase/textpresso#93]
Since it is not possible to perform a query/search unless you're logged in, there should be some sort of notice/indication as such instead of just getting no results (or in addition to getting no results).

**Comment by vanaukenk** [comment]
Would it be possible to allow users to search without a login, but then prompt them for a login when needed, e.g. customization, viewing full text?
This might allow users to perform a search just like they can in the old system yet still ask for login creds when needed?

**Comment by goldturtle** [comment]
Paul and I implemented the current policy as we need to keep better 
track of users in order to have a stronger case for grant applications. 
I can talk to him about this again when I return to L.A.

Michael.
