### ISSUE TITLE
Gene name search comparison between old and new Textpresso - TPC giving fewer results 

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#94]
Hi,

I just performed a search on TPC using the keyword 'spp-12' and the C. elegans literature  + supplementals.  

In the results, I only get 2 matches to one paper, WBPaper00027295.

If I perform the same search on the old system, I get 219 matches in 37 documents.

**Comment by goldturtle** [comment]
This was an rsync problem.
