### ISSUE TITLE
Add ability to search and display full list of category terms

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#97]
Textpresso 2.5 includes the ability, under the Categories and Synonyms tab, to search for a specific term in all categories and return a list of matching terms and their respective categories.  

It also includes the ability to browse the entire list of terms included in a given category.  

These two functionalities can be very helpful when trying to decide which categories to use for a search, or when trying to determine if a term is included in an existing category.

**Comment by goldturtle** [comment]
I have added a first version of an ontology browser to the system. It's checked in the repository, and as soon as Valerio updated the beta version, it should be available under the tab "Browsers".

I still need to work on searching *all* categories for terms, i.e., making sure there won't be performance issues. Right now you can search for terms if you know the category you want to search in. First pick one or a few category/ies you would like to search in. Then use the filter functionality to search for your particular term.

**Comment by goldturtle** [comment]
Added full search capability for terms.

**Comment by vanaukenk** [comment]
Hi - just checking; I can see the Browsers tab now, but can't seem to search a specific category yet.  Is that correct?  Thx.

**Comment by goldturtle** [comment]
Beta version is not updated yet. So for now pick a category (including children), then press OK. Category should be displayed then. If a category has too many children and you choose to include them you will be refused.

**Comment by valearna** [comment]
I've just update the beta version. Now you should see the search field.

**Comment by vanaukenk** [comment]
Okay, thank you @valearna and @goldturtle !  So far, so good :-)
